[package]
name = "denouser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.150.0"
deno_runtime = "0.76.0"
tokio = { version = "1.19", features = ["full"] }
jni = "0.19.0"
android_logger = "0.11.1"
log = "0.4.16"
